Repository nickdiego/compiledb, pull requests merged in 2018-05, with the labels that each got.

#20 Add option to exclude files that match a regular expression
  compiledb-gen-parser
Labels: enhancement

#28 Reestructure the project as a python module.
  VERSION
  setup.py
Labels: packaging

#31 Better modularize the compiledb implementation
  compiledb-gen-make
  compiledb/__main__.py
  compiledb/generator.py
  compiledb/parser.py
  compiledb/utils.py
  setup.py
  tests/test_parser.py
Labels: enhancement

#34 Fix #13: Use bashlex to preprocess substitution commands
  compiledb/commands/make.py
  compiledb/parser.py
  requirements-devel.txt
  setup.py
  tests/data/autotools_simple.txt
  tests/test_parser.py
  tox.ini
Labels: autotools
